### ISSUE TITLE
Tutorial for using travis to test eagle on line!

### ISSUE THREAD

**Issue by lk668** [saga92/eagle#53]
1. Sigin [Travis CI](https://travis-ci.org/) with your github account.

2.Add your github  repository (forked from saga92/eagle) to 'My Repositories' 

3.Commit your code to your repository. And the travis will test your  repository automatically.

**Comment by saga92** [comment]
I think contributors can test their eagle offline by local unit test and integration test. When they try to push code to master, travis can be triggered to test their code. So they don't need to test their online forked eagle.

**Comment by lk668** [comment]
Yeah, It's right.
